version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
    environment:
      HOST: 0.0.0.0
      PORT: 5555
      DB_HOST: mysql
      DB_PORT: 3313
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todolist
    depends_on:
      - mysql

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_API_URL: http://backend:8080
  #   depends_on:
  #     - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3313:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
